apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: pet-owner
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pet-owner
  name: pet-owner
  namespace: pet-owner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pet-owner
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pet-owner
    spec:
      containers:
      - image: ayadinou/tp_devops_spring_boot_app:latest
        name: pet-owner
        imagePullPolicy: IfNotPresent
        env:
          - name: DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: database-config
                key: database-host
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: database-secrets
                key: database-user
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-secrets
                key: database-password
          - name: DATABASE_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-secrets
                key: database-root-password
          - name: DATABASE_NAME
            valueFrom:
              configMapKeyRef:
                name: database-config
                key: database-name
          - name: DATABASE_PORT
            valueFrom:
              configMapKeyRef:
                name: database-config
                key: database-port
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
  namespace: pet-owner
data:
  database-host: mysqldb-service.mysql.svc.cluster.local
  database-name: pet_store
  database-port: "3306"
---
apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: pet-owner
type: Opaque
data:
  database-user: YXlhZGlub3U=
  database-password: YXlhZGlub3UxNjAx
  database-root-password: YXlhZGlub3UxNjAx
